---
- name: Install nfs client
  become: yes
  apt: >
    name={{ item }}
    state=present
  with_items:
    - nfs-common
- name: Mount NFSv3 directories
  become: yes
  mount:
    name: "{{ item.target }}"
    state: mounted
    src: "{{ item.source }}"
    fstype: "nfs"
    opts: "nfsvers=3,bg,hard,rw"
  with_items: "{{ nfsv3_target }}"

